{{- if .Values.services.qbittorrent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.qbittorrent.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: qbittorrent
{{- end }}
