{{- if .Values.services.overseerr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: overseerr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.overseerr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: overseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overseerr
    spec:
      containers:
        - name: overseerr
          image: "{{ .Values.services.overseerr.image.repository }}:{{ .Values.services.overseerr.image.tag }}"
          imagePullPolicy: {{ .Values.services.overseerr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.overseerr.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: overseerr-config
              mountPath: /config
      volumes:
        - name: overseerr-config
          hostPath:
            path: "{{ .Values.services.overseerr.config }}"
            type: Directory
{{- end}}
