---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.smb.pvcClaimName }}
  namespace: {{ .Values.common.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .Values.storage.smb.pvName }}
  storageClassName: smb