---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.smb.pvcClaimName }}
  namespace: {{ .Values.storage.smb.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-plex-smb
  storageClassName: smb