apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: {{ .Values.common.namespace }}
type: Opaque
stringData:
  username: {{ .Values.storage.smb.username | quote }}
  password: {{ .Values.storage.smb.password | quote }}
