{{- if .Values.services.autobrr.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: autobrr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.autobrr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: autobrr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autobrr
    spec:
      containers:
        - name: autobrr
          image: "{{ .Values.services.autobrr.image.repository }}:{{ .Values.services.autobrr.image.tag }}"
          imagePullPolicy: {{ .Values.services.autobrr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.autobrr.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: autobrr-config
              mountPath: /config

      volumes:
        - name: autobrr-config
          hostPath:
            path: "{{ .Values.services.autobrr.config }}"
            type: Directory
{{- end }}
