---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAGdNWHmEmaeIvsJTUxpV5zLNv4OfduH/+MIucWBj3BLSlcKbwKygoLQY7TdjOM0Bwxnb67mSGs0FIvIeGwlDLfbEmlOQ7EUwylZbGjcJTGrfxE+ZIFgAGI1z1Fh7/Md+jc2Wof7sNUFF4L6voLT+k7B9eIMUXfclf0rActEAZ9YjjM5DKJKH7maGUiA6p7fQgdyko3Qn2CXQ0Y1F6uxC65I6ir5/LUwc5KJSzfc5+WYrcrhn9kw6L0CqInZsorbmGpg15hU8mRcdKuS9kfZKcHggK7UE6eSmmiEbnJ9hfNweCjiVURKBCn/+PyCOC+RFUErHvjZQsTbFWprcZ1FMbZZsHpgBRi69uxOPRgWMT1snkHynzCBZYO04EWMLmLn2BmO8hOEcKgfyDOi9FMf7iZv/3CzPruo0kkHhmR0EzNNF5p7TZIc2HwocljSEq1ZMsQZ8g/rzi+1Xr8fKuVwgGVGWD/ryZN98/0B036WJ38tSa6KvJmd/1zx6Fgao61xswC4t8VHK285toHqZT4p7TcVk7m0Nm+fxozVrKHYFWsuQWzEqRLM62S8tRRn1gNZRRmTffWbVBN7+lxrn67oh2YatxL37nZbTSkWMD4iqFxJYqEoWJjN0fkv1uMw5awyN3dc1dv8n42Uq48CcodsEI1TBT5l2tHpnneOLDqfNMVU1KKyS0VGd+Aee/84FkgJsHb2MFCnBBYGMaXG35OsX1cTL8xagntiee4pi4lHZacIM0+r5bXboZT
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
