---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smb-creds
  namespace: default
spec:
  encryptedData:
    password: AgBPV6Glaix+t4l89D2OblFUVAJZ4rwKgdaQAk0fEtZJg4EQK+FrASB40Cew9W+4rLisPulYRUk3Bx+3pGY0b6rhdF6JwPBggH0KTyvgyh4/LDORYFyP4R68w3hML176OYnQV/vEUHKkGZaGrmoocRxjgqps+zjhS91S++FLq4FQQsss4ndUXB88H8M98JUOniWgBvft4PeA2zd374hM37Ftlzv2AItdI/JEooVLAclqN4N2E+BASrJ0LmWqQYmqzbl/4qxgxjqMwoc/8CSKXbsKxzd+OojI0REfeSY4Wo48QtLIUMOKV/EqQEJ3OYBc+ngqIf7Uyns01fyUarUeL+RRZNVEgO5orHPPIUTGLXf/3Wr3/WrpoQRQeX8whRk+BZUh/6kt+NfxRcK3Fu4udp1n47pQLlIkNDYNllDx6eCE3qdIxdBmY1YYB3MAjSSltlL2y0pbCveR/L3de8KxYa/oBExhQ/sly2r5RTFOTnf2MPXWtbTKwBwUykbxN1tEM3Sqd3IzFp+WBfPavbgJrJzDdWcOyyRrZcT4yr4yo2OS9EW7cDRSUfQK+txYguBBdYU1bdN/lcayLY7h12QPbH64k7aSjoen4k29V4LJ+nF/dNF00LsiHDme/RpiCkbQizqXtRszJ/mFlDkfIKCSYIUW/pI50objOvtupkQ95dqhVCmFWXskmyaGxeI697rF8TVre6Mhevp2amwVJuXOqnN9Ze5F
    username: AgCwQILXm3WmpztYinnu9LITdZwD4gyntuN6BQzkPUQBUHriqoxX0hXchgODQXtlvZFmO9dW7MxopcDXSsu1+vN8wzrHFSdBD35WLV76uYmTsATa1lEs9nXlLW+NlJQ8AFYdLLngbsKI7MzcRkyE0oxijzFokSxV3LguFzq9WUhF02mPcfsxdTwn3zB99VIUKcblAu/qnBNF8AMQZQoBRj9MVP9u5tOD6/Oi6J3kHqGXBIUEkuMyflxMZq+WfOwRl7WYJf6MaKDh7x24M+nezgbuii/sHJoO/iT2TlMD3Z8qy4eiu/ICuHr8x3sAjqdRXqwX9XOAmM5p7owkfdehgoSjW56x+Xv0VWfJS3M8XVAwSau0cbAJ4bhcdY27abWKdMvtDzlp4epK4GWtdZDpEKme5LP2OIXGXI2XeZwi4ohuhsBo10gXFCLzRFjmOamK1xBjooa2tZdqLHZk65vrnDR8reR4lGZM7kFfn1zMKG+0wcLPseQGiO01nRQdTuDNGPxrM0dBlghQwnuvnBkNoHlAiXdwDAWnvXv6uYSyLiuXIvfsks32x7w8TSaAFJG7tHc1L98+TBiVu2KUbopSaEDMVlDwi3PXYALmjFwFbLn6AgdaLa0JrH+oaiOxv0qbJDxhsFHWwFLjgkdLDlcJmpvpvSxvdtRtTNIoIzikL4Oe7e7AkNKeDKkumejczo5pnHpedWvMrg==
  template:
    metadata:
      name: smb-creds
      namespace: default
