---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seedbox-smb-creds
  namespace: home-server
spec:
  encryptedData:
    password: AgAS4KtEGI7aLu/bY/mmJXcDpi7is01k07wuS01KwR6X5jD8TlJrhPFdnttGNcVxHnqiniyqNaPhLNrk0ywYyYjFEQq+mxwokk74tRGK40WMpShWP0w8eFoWfVxd67I2ljByornVyUO+0LAkuJAfFgv3e4ADwCUjB93R7bLdm30St13fHS/SXe2SoN2AtrCnDevi6YFD2VjLl1gq08IZeIPCJHfkBESTOFUFD9qULzAjE1vmxU9a4Hro7CCEhzdc4nDR6z+WRpQvcXZqmoHSSCQmMkea4uQg2v+NbdoL43xWCZj1nFbnyFRANiXEPPtt5LvyNSwJhy5fUuH5CsV0evRo9KvGPCWR69YOZY1dBYLVKO6lSWoP5E1oR7Ot4c8GFaytu8IKucnNqoYNJV/TldRYj6LUWE8C0kmxIBmwMQH3pmUayIhjC7yWYtjfRPAyomp4KPP5CIKTrvWuGaTKNTz3pTxdcvkejQ56GABT7hWZ1GykG407Fqt07vrArHSaCI+NfU7HnpaoMdmgcdB9Vvesz+XbpbEiSpu0bl/knGWfz1aNZel1KSSsVjydRIgbDr1mihJAQkHTLiryyNnyVKgbCShWJkVz1sEm0IzW2oiz3EGzt2F7WqPrpzPpcjcx6b07zM/SJ5QTLMdIDyaQalJHEdhbS4kR+JZF7dyGxS86g2FB7nQ7xCAo7mFISVDpJhnkWcZu069ge/5u/J4h5fw8
    username: AgBNCW3Qmpwjr1p7SBr/GGzBEQclUfRvYe54Clhq+Kcs6zRHOOaVLYLlls++YlaeRfsHezeiRcUKYA8koqhqqGHGqrbJqqVzDDnulaa/qA8wnbn1IsjNAbVywnCnTEB5j/jgNdKUQe5b1+BCF07x5m6GyoXm2yPGKQQO7UlbJMHSimF+OCVIaS0xsRLNHSrY6ujtL83hcwPhshL1eqt2I6F8C3zj0qxmQHWt4N7r7KjjkRUmJ6Z4aLdK6ca7OPLV1vlybcn021ESLI0cOdS4gtN9OgNY22Y5umFccJftB6IwlJb0z0hes3+g5ABrv6ckzOmzXhzq6Z9ylWh91deUmtOHpUwoyV2GJrCY35UHCHLjvU+SxDIfDhMEXzAnpEvL0cgNPNS4EtD7Uo16zGWyW7h6LCbjLKgYHs7B6zAUq07xB44dAEx21RWk3Wsp78PbYqYmH9m+/y7PC9WnAtJm8qB2sk5Z9dZyLDrpNOn8lm5bcFL45j3G4+7Ng8URIsXoUsvi/P9/ux5gJWkgYCZHkzb3pleT+wkmbSOzHKeAFxBDPDqSBHnHdk3XveG/I0+LorNBWK9DLQgNkpW4yDTsK/LSLsKaU/FRCm2Yqeti20kZ4dHEYHDinK/IraZFUWxNehOB0lorH+1FHfswE4R3BmyWkWsH2sMXEzfaPL+4/mfOjTGfYFvQp6XFLiEhYom+rXw3LxXEVWJ+qNjtxBNq
  template:
    metadata:
      name: seedbox-smb-creds
      namespace: home-server
