---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smb-creds
  namespace: home-server
spec:
  encryptedData:
    password: AgBNFEQ/HRecWG12ThS7dq2Nici/hRL4wlUn+y9sj0bxNIrbjB8qzAgarr4bvUtw1B5hVU77X193gVVOuWKGrIcUqBf20P489MN57OqrXywRrpxON49Sc3xrQAD6R6QtgXLSDBhK9FMqElpwSYDQKcy2uza6f38mwx70JW0L4fwlmwIUCVB8fQXJd6fJNem9e+AA+lRV5I4Wby5AMDlNIoOLEkz3hQGKARR2usgpSFb/edxdm/0YQ2NNLElsIX+4VJ6K5S85MHf9fqCz8txGlrYg4SRF0NJHjZO++0UnVfYKE7d3LKGTN883Ig8xBU1gLDRqTTL2YhjBKwVg8h+KNaKfqXLCKRbvyFm38lnskv7b4cdIznBeNApjq7FbfL0FRISKu4RDVpVuMISGG0MMtiwVijQfKpQyHDzPAtQetYE7zJpmuRxJ8109eGZhnZjfDB64S0CJ0motqvbSX2LqZKPooUi2oYamxFqx8r91LRbvdWox/+cnjs2eOx1AklGtfWOxISDZ9gZDaGhKeKjV0ZcIY0eyMY62L3mCAcnfnDcORDupVMoT+ISBoVKewFQOHHsVDVr+jNwiJAf5JcxtCPoP8A5wAap6lYbePixUCbWIAemA/RJeYa3gy4MwR5lfLnMFTgRqA9jlWutWObtTbbo7QRPi1nEqa/D5OrWqYu2x4gt6jqRy4zOjj1MK+PHgu/ayv31Fxvaf7RumPr/eHdjiIZk3
    username: AgBSrvoY+cQfksjQIZx3ARp3oYngPBZq2CdBlsiCXov3Q+ML76CfxJCaS8ORH+kM8khaZ1JLmo6g9LwXTZRwrdyFW83+xC5LiuaiLeRiXhXd5gbAmRcYfzWdczB6/kHHSfhxC+8NHsnaFcS8hKNiM5OM3J5+sIz1lzRNDkXPXxukUftTFgaEft2/cjLaCwAuhinfpnZEYBuRkxYpOeTNvJV8K5p9HQkEcEmAZUcNGtHEJXychUBTuhcZ77mWtiD3AOy85lkt92SrBn2b/9lwcFKTNXMHz0wP3fYlCa8IA41dztZjO7Thbu81Sf2MORxmi8kNGdCBbeMtKxVGKOAopC3zyTKX+dBMFlQF/oIIIs+DG/+r/862Upuc7Hp5vz9sTnms+sEPHE/UqRqII4yhE7CmfWvtI46XYroGFVZXFEYbyV7Ee2HlVNw/2Zu9M6q8vmj0oiVgHdHGN+bogfym02WmnTsN89fMvWHffThgc7hErsYRWPBjIFJ3tIkGgxULkQFfQ2u3MvfLXCSfr2ifaQz86MmFjjJNP0S3/bn01VE6YXh+WIvnxoFy/9B1P4FEbGx/+hrim1qSFIicaYx/0PJmKx5rETyTonhzeZD385uHZ06lVRJ9uaWlIZby6VLS0IbGxta2CsHYAaLXWixN/MbPkqLyjwAsXntQu84FXxmDa3Ph7yY4RMI7mQO/0ZEXgO1BL+VXag==
  template:
    metadata:
      name: smb-creds
      namespace: home-server
