{{- if .Values.services.homepage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.homepage.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/homepage/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
        - name: init-config
          image: busybox
          command: ["sh", "-c", "cp /homepage-config/* /config-working-dir/"]
          volumeMounts:
            - name: homepage-config
              mountPath: /homepage-config
            - name: config-working-dir
              mountPath: /config-working-dir
      containers:
        - image: "{{ .Values.services.homepage.image.repository }}:{{ .Values.services.homepage.image.tag }}"
          imagePullPolicy: {{ .Values.services.homepage.image.pullPolicy }}
          name: homepage
          env:
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.homepage.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: config-working-dir
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
        - name: config-working-dir
          emptyDir: {}
{{- end}}