{{- if .Values.services.homepage.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
{{- end }}
