{{- if .Values.services.homepage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.homepage.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: homepage
{{- end }}