{{- if .Values.services.huginn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: huginn
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: huginn
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.huginn.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: huginn
{{- end }}
