{{- if .Values.services.sonarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: sonarr
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.sonarr.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sonarr
{{- end }}
