{{- if .Values.services.radarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: radarr
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.radarr.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: radarr
{{- end }}
