apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/M4NU5/UltimateHomeServer
    targetRevision: HEAD
    path: .
    helm:
      releaseName: arr-stack
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: home-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true