apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/M4NU5/UltimateHomeServer
    targetRevision: HEAD
    path: reflector
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
