apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-seedbox
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    server: 127.0.0.1    # always valid on single node k3s
    path: /
    port: 30049          # matches NodePort above
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-seedbox
  namespace: home-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: pv-seedbox
  storageClassName: ""