apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-seedbox
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: rclone-seedbox.home-server.svc.cluster.local
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-seedbox
  namespace: home-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: pv-seedbox
  storageClassName: ""