apiVersion: v1
kind: Service
metadata:
  name: rclone-seedbox
  namespace: home-server
spec:
  selector:
    app: rclone-seedbox
  ports:
    - port: 2049
      targetPort: 2049
      name: nfs
  type: ClusterIP